language: rust
before_script:
- rustup component add rustfmt
- rustup component add clippy
script:
- cargo fmt -- --check
- cargo clippy --verbose --package waiter -- -D warnings
- cargo test --verbose
